/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_snackdeng_MainActivity */

#ifndef _Included_com_example_snackdeng_MainActivity
#define _Included_com_example_snackdeng_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_snackdeng_MainActivity
 * Method:    _getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_snackdeng_MainActivity__1getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
